all: 

publish:
	scp *.html jomifred,moise@web.sourceforge.net:/home/groups/m/mo/moise/htdocs	
#	scp ../doc/tutorial/tutorial.pdf jomifred,moise@web.sf.net:/home/groups/m/mo/moise/htdocs/doc
#	scp ../doc/specification/moise-spec.pdf jomifred,moise@web.sf.net:/home/groups/m/mo/moise/htdocs/doc
